-- Insertar VIDEOJUEGOS
INSERT INTO VIDEOJUEGOS (ID_VJ, NOMBRE) VALUES (1, 'Minecraft');
INSERT INTO VIDEOJUEGOS (ID_VJ, NOMBRE) VALUES (2, 'Fortnite');

-- Insertar USUARIOS
INSERT INTO USUARIOS (ID_USER, AUTH0ID) VALUES (1, 'auth0|user123');
INSERT INTO USUARIOS (ID_USER, AUTH0ID) VALUES (2, 'auth0|user456');

-- Insertar PLANES (RAM y CPU)
INSERT INTO PLANES (ID_PLAN, ID_VIDEOJUEGO, TIPO, CANTIDAD, PRECIO_HORA, ESTADO)
VALUES (1, 1, 'RAM', 8, 5, 'DISPONIBLE');

INSERT INTO PLANES (ID_PLAN, ID_VIDEOJUEGO, TIPO, CANTIDAD, PRECIO_HORA, ESTADO)
VALUES (2, 1, 'CPU', 4, 7, 'DISPONIBLE');

INSERT INTO PLANES (ID_PLAN, ID_VIDEOJUEGO, TIPO, CANTIDAD, PRECIO_HORA, ESTADO)
VALUES (3, 2, 'RAM', 16, 10, 'NO_DISPONIBLE');

INSERT INTO PLANES (ID_PLAN, ID_VIDEOJUEGO, TIPO, CANTIDAD, PRECIO_HORA, ESTADO)
VALUES (4, 2, 'CPU', 6, 12, 'DISPONIBLE');

-- Insertar SERVICIOS
INSERT INTO SERVICIOS (ID, ID_USUARIO, ID_VIDEOJUEGO, ID_PLAN_CPU, ID_PLAN_RAM, ESTADO_PAGO, ESTADO_SERVIDOR)
VALUES (1, 1, 1, 2, 1, 'PAGADO', 'ENCENDIDO');

INSERT INTO SERVICIOS (ID, ID_USUARIO, ID_VIDEOJUEGO, ID_PLAN_CPU, ID_PLAN_RAM, ESTADO_PAGO, ESTADO_SERVIDOR)
VALUES (2, 2, 2, 4, 3, 'PENDIENTE', 'APAGADO');
